services:
  mysql:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    container_name: mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3307:3306"
    expose:
      - "3307"
    networks:
      - db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 40s
      retries: 10

  bootstrap:
    build:
      context: ./bootstrap
      dockerfile: ./Dockerfile
    container_name: bootstrap
    restart: no
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
    env_file:
      - ./.env
    networks:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    env_file:
      - ./.env
    ports:
      - "4500:80"
    expose:
      - "4500"
    networks:
      - db

networks:
  db:
    driver: bridge
